openapi: 3.2.0
info:
  title: oda Collections API
  description: ''
  license:
    name: ''
  version: 3.0.0
tags:
- name: Collections
paths:
  /collections:
    get:
      tags:
      - Collections
      operationId: utoipa_doc
      responses:
        '200':
          description: Get Collections
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollectionsResponse'
            text/html:
              schema:
                type: string
      summary: Utoipa doc
      x-summary-source: derived
components:
  schemas:
    Extent:
      type: object
      properties:
        spatial:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/Spatial'
        temporal:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/Temporal'
    CollectionId:
      type: object
      required:
      - id
      - links
      properties:
        attribution:
          type:
          - string
          - 'null'
        crs:
          type:
          - array
          - 'null'
          items:
            type: string
        description:
          type:
          - string
          - 'null'
        extent:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/Extent'
        id:
          type: string
        item_type:
          type:
          - string
          - 'null'
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
        title:
          type:
          - string
          - 'null'
    CollectionsResponse:
      type: object
      required:
      - links
      - collections
      properties:
        collections:
          type: array
          items:
            $ref: '#/components/schemas/CollectionId'
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
    Temporal:
      type: object
      properties:
        interval:
          type:
          - array
          - 'null'
          items:
            type: array
            items:
              type: string
        trs:
          type:
          - string
          - 'null'
    Link:
      type: object
      required:
      - href
      - rel
      properties:
        href:
          type: string
        hreflang:
          type:
          - string
          - 'null'
        length:
          type:
          - integer
          - 'null'
          format: int64
        rel:
          type: string
        title:
          type:
          - string
          - 'null'
        type:
          type:
          - string
          - 'null'
    Spatial:
      type: object
      properties:
        bbox:
          type:
          - array
          - 'null'
          items:
            type: array
            items:
              type: number
              format: double
        crs:
          type:
          - string
          - 'null'
